### ISSUE TITLE
Practica 9

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/actividad-9-practica-de-seguimiento-y-control-de-proyecto-entrevista-ar#1]
[Seguimiento.pdf](https://github.com/user-attachments/files/17548125/Seguimiento.pdf)

Link: https://github.com/SistemasTecTlaxiaco/reciclanexus

**Comment by josealfredo79** [comment]
Calificacion.????

**Comment by Irvingzr16** [comment]
Portada: 25
Procedimiento: 25
Figuras: 25
Resultados: 17 falta líneas de conclusión, y resultados. Pero el resto todo muy bien

**Calificación: 18**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
